### ISSUE TITLE
Having automation of creating java classes/interfaces

### ISSUE THREAD

**Issue by bmihovski** [imbacraft/dusk.nvim#16]
I'm wondering is any way to create easily Java classes/interfaces similar to idea. Like right click there new class fill the name or even the package name and the file is created for us with proper package name and initial class definition inside
I found something added, however I'm not sure is this the same thing and how to use it. https://github.com/imbacraft/dusk.nvim/blob/master/nvim/init.lua#L151

**Comment by imbacraft** [comment]
Currently Dusk.nvim supports something close to this, but not identical. 

Open nvim-tree, navigate where you want to create a new Class/Interface and press "a" to write the name (e.g. com/project/TestClass.java). Now open the newly created file and start typing "class" or "interface". You will get prompted by autocomplete to insert a Snippet. Pick the snippet and it will fill the package name and class definition.

I hope this is close to the functionality you expect.

**Comment by bmihovski** [comment]
Thanks yes definitely. How about this plugin how we can use it in our workflow https://github.com/antosha417/nvim-lsp-file-operations

**Comment by imbacraft** [comment]
This plugin does not work for jdtls. Specifically for JDTLS [this plugin](https://github.com/simaxme/java.nvim) exists. I've tested it it works. You can rename and move java classes and packages and the imports are updated automatically.

All you have to do is open nvim-tree, type "r" for rename class/package enter the new name and the plugin will take care of renaming all the imports. Then you have to type "wa" to save all the changes the plugin made. And after that I suggest space + j + u to refresh the project config.

**Comment by bmihovski** [comment]
Thanks yes this plugin is quite handy when java. About this enhancement consider to closing it in case of not so easy way to be achieved

**Comment by bmihovski** [comment]
This one is interesting for refactoring and doesn't require lsp It is supporting many languages including java https://github.com/ThePrimeagen/refactoring.nvim However, it will not help when creating new classes.

**Comment by imbacraft** [comment]
Thanks for the suggestion. I will check what this plugin can offer. For your original request I don't think there is more that Neovim can do at this time.
