### ISSUE TITLE
nvim-java poor LSP support

### ISSUE THREAD

**Issue by bmihovski** [imbacraft/dusk.nvim#2]
Hey @imbacraft thank you for the great build. I really love it and the concept of keep it minimal and easy to extend/maintain.
I saw we recently changed to nvim-java. This plugin is great in a way that is working out of the box.
However, there is one downside though. It lacking of LSP features which are important to the modern Java development. Like code actions and many other useful jdtls features. I know the plugin is under active development and the gaps can be filled out soon. 
I brought the attention to nvim-java maintainers https://github.com/nvim-java/nvim-java/issues/161 and is not clear when will have the features. 
```
@bmihovski nvim-java (this plugin) and nvim-jdtls are two different plugins for Neovim. In nvim-jdtls has refactoring features. Those are not yet implemented in nvim-java. If you have plans to use nvim-java then you should remove nvim-jdtls.
```
Based on that is any possibility to switch back to nvim-jdtls until the nvim-java improves?

By the way I forked you repo and added some features on top of it like some handy plugins and Python and C++ support. https://github.com/bmihovski/dusk.nvim
Feel free to add the extensions or let me know if you want me to create a PR with some of them.

Cheers

**Comment by imbacraft** [comment]
Hello @bmihovski, thank you for bringing this to my attention. I experimented with [nvim-java](https://github.com/nvim-java/nvim-java) because of these reasons:

1. It has excellent way of setting up DAP debugger
2. It supports java active profiles 
3. It supports smart java mainclass execution

Yesterday I noticed the issue you are raising about the missing refactoring features.
I also noticed another issue: nvim-java does not support working on multiple projects simultaneously - When I open a second buffer from another project, jdtls does not behave correctly.

What I will try to do is get the above features that I want from nvim-java and migrate back to nvim-jdtls. If that's not possible I think I will stay with nvim-java for a while, because I value those features above the superior refactoring capacities of nvim-jdtls for now.

With regards to the features you added, feel free to open a PR, although I would like to keep this config suited for Java development. If not too many new plugins are needed for Python and C++ support, then I will merge it.

Thank you for your time to try out this config and for your excellent observation.

Kind regards,
imbacraft

**Comment by bmihovski** [comment]
Thank you I think your approach make sense the nvim-java is just a wrapper on the top of jdtls. 
The lsp-zero jdtls approach is much cleaner and with less dependencies.
The nvim-java is designed to work with lazy neovim which is coming with some assumptions.
Also the plugin from time to time contains some bugs which may block the dusk to operate properly for example https://github.com/nvim-java/nvim-java/issues/190 

This is due to the fact of high abstraction when this plugin. Which is coming with pros and cons.

In regards of the plugins sure I can keep them not bound to C++ and Python.

However, do you have any ideas how to add a support for more languages by offloading their specifics to separate files like you did with jdtls ?

I'm doing Java by myself but also Python and C++ so keeping Dusk simple and extensible without heavy abstraction could be very desirable.

Greetings from Bulgaria :)

**Comment by bmihovski** [comment]
@imbacraft I have one more additional question if you don't mind. I'm planning to continue to use the old jdtls implementation for now and to reinstate the deleted files in my fork. My question is do we still need jdtls2.lua and jdtls3.lua and what is the purpose of having them?

**Comment by imbacraft** [comment]
@bmihovski For other languages configurations, you can write a custom function for your language in the handlers section of lsp-zero initialization in init.lua.

```lua  

handlers = {
    function(server_name)
      require('lspconfig')[server_name].setup({
           require("your.language.setup.file")
})
    end,
}
```

For more information, consult: [lsp-zero custom handlers](https://lsp-zero.netlify.app/v3.x/guide/integrate-with-mason-nvim.html)

With regards to jdtls2.lua and jdtls3.lua , these were already my attempts to integrate nvim-java with nvim-jdtls. They were accidentally pushed. You can safely delete them.

My greetings from Thessaloniki, Greece :)

**Comment by bmihovski** [comment]
Thank you! I got the idea I only need to consider when we need a specific DAP. Shall we keep this issue open until nvim-java integration is concluded and to communicate here or you prefer to be closed?

**Comment by imbacraft** [comment]
I think it's best to leave this issue open as long as I'm working on it. It will be helpful for people to be aware of this discrepancy between nvim-java and nvim-jdtls.

Stay tuned for updates!

**Comment by imbacraft** [comment]
@bmihovski Latest [commit](https://github.com/imbacraft/dusk.nvim/commit/8a3a25faceed52791d04816f37bca44ba43104e0) aims to address this issue. I tried it out on my projects and the functionality provided by nvim-jdtls seems to work. 

Please try it out for yourself, because I'm not familiar with these functions. You can see some normal mappings under  Leader+j and I added some visual mappings (vmappings) under Leader + J.

Looking forward to your feedback.

Please note that multiple projects support on the same nvim instance is still not possible. I will try to address this in a future update.

**Comment by bmihovski** [comment]
@imbacraft Thanks for the changes great work it looks amazing now! 
Here is my setup https://github.com/bmihovski/dusk.nvim
However here are the first issues when running the tests from a class
```bash
[INFO  24.05.2024 (пт) 22:30:51] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:20: run current test class
[ERROR 24.05.2024 (пт) 22:30:51] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:23: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:22>
[ERROR 24.05.2024 (пт) 22:30:51] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
failed to run the current test class
...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:28: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:23: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:22>
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'step'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:54: in function <...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:19>
[INFO  24.05.2024 (пт) 22:31:19] .../share/nvim/lazy/nvim-java/lua/java/startup/nvim-dep.lua:40: check neovim plugin dependencies
[INFO  24.05.2024 (пт) 22:31:19] ...lazy/nvim-java/lua/java/startup/lspconfig-setup-wrap.lua:11: wrap lspconfig.java.setup function to inject a custom java config
[INFO  24.05.2024 (пт) 22:31:19] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:14: add LspAttach event handlers to setup dap adapter & config
[INFO  24.05.2024 (пт) 22:31:50] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:20: run current test class
[ERROR 24.05.2024 (пт) 22:31:50] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:23: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:22>
[ERROR 24.05.2024 (пт) 22:31:50] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
failed to run the current test class
...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:28: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:23: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:22>
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'step'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:54: in function <...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:19>
[INFO  24.05.2024 (пт) 22:32:56] .../share/nvim/lazy/nvim-java/lua/java/startup/nvim-dep.lua:40: check neovim plugin dependencies
[INFO  24.05.2024 (пт) 22:32:56] ...lazy/nvim-java/lua/java/startup/lspconfig-setup-wrap.lua:11: wrap lspconfig.java.setup function to inject a custom java config
[INFO  24.05.2024 (пт) 22:32:56] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:14: add LspAttach event handlers to setup dap adapter & config
[INFO  24.05.2024 (пт) 22:33:23] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:20: run current test class
[ERROR 24.05.2024 (пт) 22:33:23] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:23: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:22>
[ERROR 24.05.2024 (пт) 22:33:23] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
failed to run the current test class
...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:28: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:23: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:22>
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'step'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:54: in function <...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:19>

[INFO  24.05.2024 (пт) 22:40:44] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:52: run current test method
[ERROR 24.05.2024 (пт) 22:40:44] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:55: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:54>
[ERROR 24.05.2024 (пт) 22:40:44] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
failed to run the current test method
...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:28: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:55: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:54>
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'step'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:54: in function <...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:19>
```

**Comment by bmihovski** [comment]
here is the java core logs

[DEBUG 24.05.2024 (пт) 22:49:40] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:23: generating jdtls config
[DEBUG 24.05.2024 (пт) 22:49:40] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:87: generated jdtls setup config:  {
  cmd = { "java", "-Declipse.application=org.eclipse.jdt.ls.core.id1", "-Dosgi.bundles.defaultStartLevel=4", "-Declipse.product=org.eclipse.jdt.ls.core.product", "-Dosgi.checkConfiguration=true", "-Dosgi.sharedConfiguration.area=/home/boyanmihovski/.local/share/nvim/mason/share/jdtls/config", "-Dosgi.sharedConfiguration.area.readOnly=true", "-Dosgi.configuration.cascaded=true", "-Xms1G", "--add-modules=ALL-SYSTEM", "--add-opens", "java.base/java.util=ALL-UNNAMED", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "-javaagent:/home/boyanmihovski/.local/share/nvim/mason/share/lombok-nightly/lombok.jar", "-jar", "/home/boyanmihovski/.local/share/nvim/mason/share/jdtls/plugins/org.eclipse.equinox.launcher.jar", "-configuration", "/home/boyanmihovski/.cache/nvim/jdtls/config", "-data", "/home/boyanmihovski/.cache/nvim/jdtls/workspaces/_home_boyanmihovski_Privatespace_.dotfiles_nvim_.config" },
  init_options = {
    bundles = { "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-jupiter-api_5.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-jupiter-engine_5.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-jupiter-migrationsupport_5.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-jupiter-params_5.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-platform-commons_1.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-platform-engine_1.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-platform-launcher_1.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-platform-runner_1.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-platform-suite-api_1.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-platform-suite-commons_1.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-platform-suite-engine_1.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/junit-vintage-engine_5.9.3.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/org.apiguardian.api_1.1.2.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/org.eclipse.jdt.junit4.runtime_1.3.0.v20220609-1843.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/org.eclipse.jdt.junit5.runtime_1.1.100.v20220907-0450.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/org.opentest4j_1.2.0.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-test/com.microsoft.java.test.plugin-0.40.1.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-debug-adapter/com.microsoft.java.debug.plugin-0.50.0.jar", "/home/boyanmihovski/.local/share/nvim/mason/share/java-debug-adapter/com.microsoft.java.debug.plugin.jar",
      <metatable> = <1>{
        __index = <table 1>,
        concat = <function 1>,
        every = <function 2>,
        find = <function 3>,
        flatten = <function 4>,
        for_each = <function 5>,
        includes = <function 6>,
        join = <function 7>,
        map = <function 8>,
        new = <function 9>,
        push = <function 10>
      }
    },
    extendedClientCapabilities = {
      advancedExtractRefactoringSupport = true,
      advancedOrganizeImportsSupport = true,
      classFileContentsSupport = true,
      executeClientCommandSupport = true,
      generateConstructorsPromptSupport = true,
      generateDelegateMethodsPromptSupport = true,
      generateToStringPromptSupport = true,
      hashCodeEqualsPromptSupport = true,
      inferSelectionSupport = { "extractMethod", "extractVariable", "extractConstant", "extractVariableAllOccurrence" },
      moveRefactoringSupport = true,
      overrideMethodsPromptSupport = true
    },
    workspace = "/home/boyanmihovski/.cache/nvim/jdtls/workspaces/_home_boyanmihovski_Privatespace_.dotfiles_nvim_.config"
  },
  root_dir = <function 11>
}

**Comment by bmihovski** [comment]
With this config is working fine https://github.com/bmihovski/neovim-cpp

**Comment by bmihovski** [comment]
Here is with the original dusk it looks like the issue is with my fork

[INFO  24.05.2024 (пт) 23:49:33] .../share/nvim/lazy/nvim-java/lua/java/startup/nvim-dep.lua:40: check neovim plugin dependencies
[INFO  24.05.2024 (пт) 23:49:37] ...local/share/nvim/lazy/nvim-java/lua/java/utils/mason.lua:66: check mason dependecies
[INFO  24.05.2024 (пт) 23:50:23] .../share/nvim/lazy/nvim-java/lua/java/startup/nvim-dep.lua:40: check neovim plugin dependencies
[INFO  24.05.2024 (пт) 23:50:23] ...lazy/nvim-java/lua/java/startup/lspconfig-setup-wrap.lua:11: wrap lspconfig.java.setup function to inject a custom java config
[INFO  24.05.2024 (пт) 23:50:23] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:14: add LspAttach event handlers to setup dap adapter & config
[INFO  24.05.2024 (пт) 23:51:03] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:49: setup java dap config & adapter
[INFO  24.05.2024 (пт) 23:51:03] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:23: configuring dap
[DEBUG 24.05.2024 (пт) 23:51:03] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:83: set dap adapter callback function
[INFO  24.05.2024 (пт) 23:52:22] .../share/nvim/lazy/nvim-java/lua/java/startup/nvim-dep.lua:40: check neovim plugin dependencies
[INFO  24.05.2024 (пт) 23:52:22] ...lazy/nvim-java/lua/java/startup/lspconfig-setup-wrap.lua:11: wrap lspconfig.java.setup function to inject a custom java config
[INFO  24.05.2024 (пт) 23:52:22] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:14: add LspAttach event handlers to setup dap adapter & config
[INFO  24.05.2024 (пт) 23:52:35] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:49: setup java dap config & adapter
[INFO  24.05.2024 (пт) 23:52:35] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:23: configuring dap
[DEBUG 24.05.2024 (пт) 23:52:35] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:83: set dap adapter callback function
[INFO  24.05.2024 (пт) 23:53:52] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:41: debug current test method
[DEBUG 24.05.2024 (пт) 23:53:52] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:54: running the current method
[DEBUG 24.05.2024 (пт) 23:53:52] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:67: finding the current test method
[INFO  24.05.2024 (пт) 23:54:35] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:52: run current test method
[DEBUG 24.05.2024 (пт) 23:54:35] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:54: running the current method
[DEBUG 24.05.2024 (пт) 23:54:35] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:67: finding the current test method
[INFO  24.05.2024 (пт) 23:58:06] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:41: debug current test method
[DEBUG 24.05.2024 (пт) 23:58:06] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:54: running the current method
[DEBUG 24.05.2024 (пт) 23:58:06] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:67: finding the current test method
[INFO  25.05.2024 (сб)  0:05:06] .../share/nvim/lazy/nvim-java/lua/java/startup/nvim-dep.lua:40: check neovim plugin dependencies
[INFO  25.05.2024 (сб)  0:05:06] ...lazy/nvim-java/lua/java/startup/lspconfig-setup-wrap.lua:11: wrap lspconfig.java.setup function to inject a custom java config
[INFO  25.05.2024 (сб)  0:05:06] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:14: add LspAttach event handlers to setup dap adapter & config
[INFO  25.05.2024 (сб)  0:05:13] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:49: setup java dap config & adapter
[INFO  25.05.2024 (сб)  0:05:13] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:23: configuring dap
[DEBUG 25.05.2024 (сб)  0:05:13] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:83: set dap adapter callback function
[INFO  25.05.2024 (сб)  0:06:17] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:41: debug current test method
[DEBUG 25.05.2024 (сб)  0:06:17] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:54: running the current method
[DEBUG 25.05.2024 (сб)  0:06:17] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:67: finding the current test method
[INFO  25.05.2024 (сб)  0:09:20] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:41: debug current test method
[DEBUG 25.05.2024 (сб)  0:09:20] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:54: running the current method
[DEBUG 25.05.2024 (сб)  0:09:20] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:67: finding the current test method
[INFO  25.05.2024 (сб)  0:10:33] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:52: run current test method
[DEBUG 25.05.2024 (сб)  0:10:33] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:54: running the current method
[DEBUG 25.05.2024 (сб)  0:10:33] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:67: finding the current test method
[INFO  25.05.2024 (сб)  0:10:51] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:41: debug current test method
[DEBUG 25.05.2024 (сб)  0:10:51] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:54: running the current method
[DEBUG 25.05.2024 (сб)  0:10:51] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:67: finding the current test method
[INFO  25.05.2024 (сб)  0:11:12] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:31: debug current test class
[DEBUG 25.05.2024 (сб)  0:11:12] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:44: running the current class
[INFO  25.05.2024 (сб)  0:12:40] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:52: run current test method
[DEBUG 25.05.2024 (сб)  0:12:40] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:54: running the current method
[DEBUG 25.05.2024 (сб)  0:12:40] ...i/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:67: finding the current test method


boyanmihovski/.cache/nvim/jdtls/config/org.eclipse.osgi/108/0/.cp", "/home/boyanmihovski/.cache/nvim/jdtls/config/org.eclipse.osgi/53/0/.cp", "/home/boyanmihovski/.cache/nvim/jdtls/config/org.eclipse.osgi/100/0/.cp",
    <metatable> = <1>{
      __index = <table 1>,
      new = <function 1>,
      push = <function 2>
    }
  },
  cwd = "/home/boyanmihovski/Workspace/-service",
  javaExec = "/home/boyanmihovski/.sdkman/candidates/java/21.0.2-amzn/bin/java",
  mainClass = "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner",
  modulePaths = {
    <metatable> = <table 1>
  },
  name = "Launch All Java Tests",
  noDebug = false,
  projectName = "service",
  request = "launch",
  type = "java",
  vmArgs = "-ea"
}
[DEBUG 25.05.2024 (сб)  0:11:12] ...hare/nvim/lazy/nvim-java-dap/lua/java-dap/api/runner.lua:42: running "before" callback
[DEBUG 25.05.2024 (сб)  0:11:12] ...share/nvim/lazy/nvim-java-dap/lua/java-dap/api/setup.lua:28: creating dap adapter for java
[DEBUG 25.05.2024 (сб)  0:11:12] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:62: sending LSP request: workspace/executeCommand
[DEBUG 25.05.2024 (сб)  0:11:12] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:69: workspace/executeCommand success! response:  39681
[DEBUG 25.05.2024 (сб)  0:11:12] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:62: sending LSP request: workspace/executeCommand
[DEBUG 25.05.2024 (сб)  0:11:12] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:69: workspace/executeCommand success! response:  2
[DEBUG 25.05.2024 (сб)  0:11:12] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:62: sending LSP request: workspace/executeCommand
[DEBUG 25.05.2024 (сб)  0:11:12] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:69: workspace/executeCommand success! response:  { {},
[DEBUG 25.05.2024 (сб)  0:12:40] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:62: sending LSP request: workspace/executeCommand
[DEBUG 25.05.2024 (сб)  0:12:40] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:69: workspace/executeCommand success! response:  {}

**Comment by imbacraft** [comment]
Hello @bmihovski , thank you for testing the integration with nvim-jdtls.

I wasn't able to reproduce your original issue, but I'm glad it was your fork.

Latest commits on master improve the folder structure of the jdtls settings and lsp default config files.
I also added some keymaps for debug test methods and classes (under Leader + d).

I think we might consider this issue resolved.

**Comment by bmihovski** [comment]
@imbacraft Thank you the latest changes are amazing. Exact missing part.
About my issue it ends up the current java changes are not compatible with the plugin below. This drove me nuts until I found it the current jdtls setup is not working with this plugin when installed in a standard way (without nvim-java) then is fine.

```lua
	-- save buffers
	{
		"olimorris/persisted.nvim",
		lazy = false,
		config = function()
			require("persisted").setup({
				ignored_dirs = {
					"~/.config",
					"~/.local/nvim",
					{ "/", exact = true },
					{ "/tmp", exact = true },
				},
				autoload = true,
				on_autoload_no_session = function()
					vim.notify("No existing session to load.")
				end,
			})
		end,
	},
```
The last spotted side effect is the sonarlint stopped working only when java files (when c++ is fine, and previously was fine with java). 
Most likely you know sonarlint and is very helpful especially for java development.

```lua
  {
    "https://gitlab.com/schrieveslaach/sonarlint.nvim",
    dependencies = { "mfussenegger/nvim-jdtls" },
    event = { "BufRead", "BufNewFile" },
    opts = {
      handlers = {},
    },
    config = function()
      require("sonarlint").setup({
        server = {
          cmd = {
            "sonarlint-language-server",
            -- Ensure that sonarlint-language-server uses stdio channel
            "-stdio",
            "-analyzers",
            -- paths to the analyzers you need, using those for python and java in this example
            vim.fn.expand("$MASON/share/sonarlint-analyzers/sonarpython.jar"),
            vim.fn.expand("$MASON/share/sonarlint-analyzers/sonarcfamily.jar"),
            vim.fn.expand("$MASON/share/sonarlint-analyzers/sonarjava.jar"),
          },
          settings = {
            sonarlint = {
              pathToCompileCommands = vim.fn.getcwd() .. "/compile_commands.json",
            },
          },
        },
        filetypes = {
          -- Tested and working
          "python",
          "cpp",
          -- Requires nvim-jdtls, otherwise an error message will be printed
          "java",
        },
      })
    end,
  },
```
That's for now I will let you know in case of something else

**Comment by bmihovski** [comment]
and maybe one small improvement the jdtls messages to be reduced when switching between two files from the same project. Do need to index every time even without any code changes in place?

**Comment by imbacraft** [comment]
@bmihovski Thank you for suggesting the sonarlint plugin. I will start work to integrate it with nvim-jdtls and nvim-java.

However, I think that for adding this sonarlint plugin, it would be better to open a new issue, so I can track the work done.

Also, I will reduce the notifications emitted by fidget.nvim to address the status messages of jdtls printed.

For now, I will mark the original issue as resolved.
