### ISSUE TITLE
Java lang server is not compatible with persisted.nvim

### ISSUE THREAD

**Issue by bmihovski** [imbacraft/dusk.nvim#3]
The current java changes are not compatible with the plugin below. This drove me nuts until I found it the current jdtls setup is not working with this plugin when installed in a standard way (without nvim-java) then is fine.
Here is the plugin which can't be integrated
	-- save buffers
	{
		"olimorris/persisted.nvim",
		lazy = false,
		config = function()
			require("persisted").setup({
				ignored_dirs = {
					"~/.config",
					"~/.local/nvim",
					{ "/", exact = true },
					{ "/tmp", exact = true },
				},
				autoload = true,
				on_autoload_no_session = function()
					vim.notify("No existing session to load.")
				end,
			})
		end,
	},
Here  is some stacktrace from the server found in the lsp log

```bash
[INFO  24.05.2024 (пт) 22:30:51] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:20: run current test class
[ERROR 24.05.2024 (пт) 22:30:51] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:23: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:22>
[ERROR 24.05.2024 (пт) 22:30:51] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
failed to run the current test class
...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:28: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:23: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:22>
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'step'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:54: in function <...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:19>
[INFO  24.05.2024 (пт) 22:31:19] .../share/nvim/lazy/nvim-java/lua/java/startup/nvim-dep.lua:40: check neovim plugin dependencies
[INFO  24.05.2024 (пт) 22:31:19] ...lazy/nvim-java/lua/java/startup/lspconfig-setup-wrap.lua:11: wrap lspconfig.java.setup function to inject a custom java config
[INFO  24.05.2024 (пт) 22:31:19] ...ki/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:14: add LspAttach event handlers to setup dap adapter & config
[INFO  24.05.2024 (пт) 22:31:50] ...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:20: run current test class
[ERROR 24.05.2024 (пт) 22:31:50] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:23: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:22>
[ERROR 24.05.2024 (пт) 22:31:50] ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:26: 
failed to run the current test class
...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:28: 
could not find an active jdtls client
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function <...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:17>
	...local/share/nvim/lazy/nvim-java/lua/java/utils/jdtls.lua:9: in function 'jdtls'
	...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:23: in function <...i/.local/share/nvim/lazy/nvim-java/lua/java/api/test.lua:22>
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'step'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:54: in function <...e/nvim/lazy/nvim-java-
```

**Comment by bmihovski** [comment]
@imbacraft it looks I managed to make it to work by deleting nvim cache directory. Feel free to test it from your side and to include to the list with the plugins. This plugin is simple however, it is improving the developer experience quite a lot.
The issue can be closed if you like.

**Comment by imbacraft** [comment]
@bmihovski I'm glad it worked for you, because yesterday I did not manage to make it work.

Can you explain some use cases where this plugin can improve the developer experience?
So far I never thought of using a session plugin for neovim.

**Comment by bmihovski** [comment]
@imbacraft it is not working great though Sometimes we need to restart nvim in order to load the java lang server. The usecases are we are  we  working  on several projects and a project is opened it load the last opened buffers there (unique per project). This is speeding the things a lot when is required to restart neovim (let say open your neovim every morning)
Intelij has similar function but this one is much better

**Comment by imbacraft** [comment]
@bmihovski If you have managed to make it work reliably, you can open a PR and include this plugin commented out for anyone that needs it. Thank you!

**Comment by bmihovski** [comment]
Sure, I trying to make it more reliable. I can suggest few more plugins if you like with one thing in mind to keep Dusk lightweight. I think we lacking of docker and DB support which are essential  for now  a days development.

**Comment by imbacraft** [comment]
Certainly go ahead. For now I use Docker desktop and DBeaver, but let's see what the neovim community has come up with.

**Comment by imbacraft** [comment]
Latest commit on development branch reverts back to nvim-jdtls. Therefore, this issue should be resolved. Kindly confirm.

**Comment by bmihovski** [comment]
Thanks that’s great news I’m pretty much sure the issue is nvim-jdtls This package is working not so stable even without the the persistent plugin from time to time I need to reset the workspace to be able to run the code. The tests are reporting success even I made them to fail
