### ISSUE TITLE
Sonarlint is not rendering java files with the latest java lsp changes but working fine when C++/Python files (different lsp)

### ISSUE THREAD

**Issue by bmihovski** [imbacraft/dusk.nvim#4]
The last spotted side effect is the sonarlint stopped working only when java files (when c++ is fine, and previously was fine with java).
Most likely you know sonarlint and is very helpful especially for java development.

  {
    "https://gitlab.com/schrieveslaach/sonarlint.nvim",
    dependencies = { "mfussenegger/nvim-jdtls" },
    event = { "BufRead", "BufNewFile" },
    opts = {
      handlers = {},
    },
    config = function()
      require("sonarlint").setup({
        server = {
          cmd = {
            "sonarlint-language-server",
            -- Ensure that sonarlint-language-server uses stdio channel
            "-stdio",
            "-analyzers",
            -- paths to the analyzers you need, using those for python and java in this example
            vim.fn.expand("$MASON/share/sonarlint-analyzers/sonarpython.jar"),
            vim.fn.expand("$MASON/share/sonarlint-analyzers/sonarcfamily.jar"),
            vim.fn.expand("$MASON/share/sonarlint-analyzers/sonarjava.jar"),
          },
          settings = {
            sonarlint = {
              pathToCompileCommands = vim.fn.getcwd() .. "/compile_commands.json",
            },
          },
        },
        filetypes = {
          -- Tested and working
          "python",
          "cpp",
          -- Requires nvim-jdtls, otherwise an error message will be printed
          "java",
        },
      })
    end,
  },

Here is the mason part of the installation

https://github.com/bmihovski/dusk.nvim/blob/master/nvim/init.lua#L640C1-L670C11

Here are some logs  messages from lsp.log

```
[WARN][2024-05-25 12:50:44] ...m/lsp/client.lua:1023	"server_request: no handler found for"	"sonarlint/filterOutExcludedFiles"
[WARN][2024-05-25 12:50:44] ...m/lsp/client.lua:1023	"server_request: no handler found for"	"sonarlint/filterOutExcludedFiles"
[ERROR][2024-05-25 12:51:10] .../vim/lsp/rpc.lua:770	"rpc"	"/home/boyanmihovski/.sdkman/candidates/java/current/bin/java"	"stderr"	"May 25, 2024 12:51:10 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation\nWARNING: Unmatched cancel notification for request id 106\n"
[ERROR][2024-05-25 12:51:10] .../vim/lsp/rpc.lua:770	"rpc"	"/home/boyanmihovski/.sdkman/candidates/java/current/bin/java"	"stderr"	"May 25, 2024 12:51:10 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation\nWARNING: Unmatched cancel notification for request id 117\n"
```

Note:
The sonarlit plugin is working perfectly when standard jdtls installation

**Comment by imbacraft** [comment]
@bmihovski I am working on this now. When this plugin was working for you, did you get all the diagnostics from Sonarlint to display in the Trouble.nvim diagnostics list?

My current work manages to integrate all of them (nvim-java, nvim-jdtls, sonarlint), but the diagnostics are displayed only for the opened buffer.

You can check out how it works now on the development branch.

Also, I never managed to make it work with event = { "BufRead", "BufNewFile" }.

**Comment by bmihovski** [comment]
Hi @imbacraft thanks for the hint. Actually, based on your comment I managed to make it to work by deleting the nvim cache dir. In regards of trouble could provide more information how are using it there? 
In addition feel free to close this issue.

**Comment by imbacraft** [comment]
@bmihovski In Trouble.nvim panel, I can see project-wide diagnostic reports from LSP and buffer-only reports from sonarlint.

I expected project-wide reports from sonarlint also.

If that's expected behavior from sonarlint, ignore this comment.

**Comment by bmihovski** [comment]
I'm usually using it like this when trouble

Trouble quickfix

**Comment by imbacraft** [comment]
Seems to be working as intended on master
